### ISSUE TITLE
Reverse Proxy Subdirectory Support

### ISSUE THREAD

**Issue by zachbunyard** [LukeChannings/moviematch#10]
Reverse proxy via Nginx works without much effort, but I've been unable to put it in a subdirectory.  Is this supported? Example:
URL is https://domain.com/moviematch instead of https://domain.com

Every time I try to load the page it simply said 'Not Found'.  Google Chrome dev tools show that a 404 error is occurring.  I have other applications running behind a reverse proxy using subdirectories and would love to add this to the mix.

Please let me know if I can provide any further details.

**Comment by flying-sausages** [comment]
You beat me to this

**Comment by LukeChannings** [comment]
I've added support for setting the root path in [v1.2.0](https://github.com/LukeChannings/moviematch/releases/tag/v1.2.0), here's how it works:

Start MovieMatch with `ROOT_PATH=/moviematch`, and use an nginx config that looks like this:

```
http {
  server {
    listen 9000;

    location ^~ /moviematch/ {
        proxy_pass http://localhost:8000/;
        proxy_set_header Upgrade $http_upgrade;
    }
  }
}

```

**Comment by Mobrockers** [comment]
@LukeChannings this is actually not how I would expect a ROOT_PATH property to work, and also not how proxies by default redirect. Normally the application itself would also listen on /moviematch with a ROOT_PATH/BASE_URL set. See: Radarr,Sonarr etc.

**Comment by flying-sausages** [comment]
Thanks! Super weird I only got the notification for this today...
