### ISSUE TITLE
[Bug] Unable to Connect via Reverse Proxy

### ISSUE THREAD

**Issue by LeLawnGames** [LukeChannings/moviematch#107]
I'm receiving the following error in the logs when attempting to access Moviematch via a reverse proxy (setup with Nginx Proxy Manager).

[my computer]:~$ docker logs moviematch
INFO Listening on port 8000
INFO Got a login: {"name":"Bender","roomCode":"KXJG"}
INFO Listening on port 8000
ERROR Error: request is not acceptable
    at acceptWebSocket (https://deno.land/std@0.79.0/ws/mod.ts:437:9)
    at WebSocketServer.connect (file:///app/src/util/websocketServer.ts:38:26)
    at file:///app/src/index.ts:30:11

Unsure what's causing this but any help much appreciated!

Running Docker image (latest) in Ubuntu

**Comment by LukeChannings** [comment]
You should check that nginx is properly configured to reverse proxy WebSockets

**Comment by LeLawnGames** [comment]
This is what I have in my custom locations on NPM. 

proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";

I've tried a few troubleshooting issues but I'm having success with all my other proxies so wondering if I'm missing some understanding on making sure Moviematch is being communicated to properly?

**Comment by LeLawnGames** [comment]
Solved, very dumb problem I was pointing my duckdns to the wrong ip lol -- thanks for responding!
