### ISSUE TITLE
[Feature Request] Filter out watched media

### ISSUE THREAD

**Issue by 8bitgentleman** [LukeChannings/moviematch#15]
**Is your feature request related to a problem? Please describe.**
Right now movies that I have already watched with plex show up in the stack as options.

**Describe the solution you'd like**
I would like a toggle option when creating a room that allows me to only show media that has not been watched by a certain user. 

**Describe alternatives you've considered**
Another option would be to have each user log-in with plex (maybe using #14 ) and then into a room. Then moviematch could only show each user media that they have not watched.

**Additional context**
Great job on putting this together it's a great addition to my Plex server!

**Comment by sifotes** [comment]
Not sure exactly this would be implemented without having each user log in (difficult to convince others) but I'd be ok with at least filtering out the library items that I've already watched. (only storing my login info)

**Comment by flying-sausages** [comment]
#14 could solve that

**Comment by LukeChannings** [comment]
I'm thinking of something along these lines...

![Mobile - Log in - Valid](https://user-images.githubusercontent.com/461449/101991415-6e6ef280-3ca4-11eb-8b24-c95f6eb3c8f3.jpg)

![Mobile - Create  Room - With 2 filters](https://user-images.githubusercontent.com/461449/101991418-73cc3d00-3ca4-11eb-9440-46cb736a4cb6.jpg)

**Comment by flying-sausages** [comment]
what will determine what's watched and what isn't?

**Comment by 8bitgentleman** [comment]
@LukeChannings that looks exactly like what I had in mind!

**Comment by LukeChannings** [comment]
> what will determine what's watched and what isn't?

I'm not 100% sure yet. It's easy enough to do it based on the administrator's watched status, but that's probably not the best. 

I'm mostly exploring the UX here.

Another option may be to require participants to be logged in on a session-by-session basis, which makes checking the watched status a bit easier.

**Comment by kernelkaribou** [comment]
One idea, have it be a checkbox for the room generation (not sure if that would complicate the backend). So room code "1234" is only showing unwatched movies for the selected library. Something I was thinking would be awesome and saw this.

**Comment by sifotes** [comment]
> It's easy enough to do it based on the administrator's watched status, but that's probably not the best.
 
I think this would be good enough for most cases, and would be pretty streamlined in terms of usability compared to having everyone log into their own Plex account. Even better if Plex SSO get's implemented.

**Comment by Mushin** [comment]
I would go one step further with the filtering and e.g. offer the movies with highest critic rating (or recent releases) first, or give them a higher weighting to appear sooner.

**Comment by jeremysherriff** [comment]
If I understand the project goal correctly, #14 isn't necessary for this feature. You're attempting to assist in a group of people selecting what media to watch (together, presumably) - therefore the watched/unwatched status is either mostly irrelevant (eg a group of friends, who individually have watched many different movies and therefore accept that some in the group will likely have already seen the chosen title), or it is very relevant (a couple who are attempting to decide what to watch next on a shared screen, therefore using a specific Plex account).  In this situation, the token used to connect to the Plex server is likely from the account that they are going to use.  Attempting to understand the different watched/unwatched status of media across a number of Plex accounts seems to me to be an edge case.

For me right now, the value of this project is diminished severely by showing watched movies.  My library has ~1,500 titles, but only around are 60 unwatched.  The chances of the card stack presenting me and my partner with unwatched movies to chose from is very slim.

**Comment by LukeChannings** [comment]
@jeremysherriff 

Note that if you want to create a room with unplayed media you can use the Unplayed filter like shown below:

<img src="https://user-images.githubusercontent.com/461449/118373962-60a1fe00-b5b1-11eb-8da9-5b764603a7fa.jpeg"  width="300" alt="Create Room" />

This was previously broken but is working correctly in 2.0.0-beta.2

**Comment by 8bitgentleman** [comment]
@LukeChannings Just checked out beta-2, amazing progress! As far as I'm concerned this feature now exists, I'll go ahead and close the request. Thanks!

**Comment by jeremysherriff** [comment]
Thanks @LukeChannings I've only looked at the stable branch so far, I'll
check out v2
