### ISSUE TITLE
[Bug] Cannot hit engage button when running through Synology reverse proxy 

### ISSUE THREAD

**Issue by KyleMcKnz** [LukeChannings/moviematch#16]
**Describe the bug**
Have set up a reverse proxy using Synology's built in application portal and can access Webapp (pointing to sub.domain.com) but after entering name and room code hitting engage button does nothing. When accessing the Webapp from the localhost it behaves as expected.

Running latest version 1.2

**To Reproduce**
Set up reverse proxy using Synology's application portal
Access Webapp via subdomain
Fill-out required fields
Hit Engage button

**Expected behavior**
Proceed to use Webapp as intended

**Screenshots**
Docker logs
![image](https://user-images.githubusercontent.com/75816931/101846011-e231d200-3bb4-11eb-9579-021c69ce44f1.png)

**Desktop (please complete the following information):**
 - OS: Windows and IOS
 - Browser: Chrome, Safari (Desktop and IOS)
 - Version 1.2

**Comment by KyleMcKnz** [comment]
Ignore this, found the section within Synology's Application Portal to allow webhook.

For anyone in the future simply edit your reverse proxy rule. Select Customer Headers - Dropdown menu besides Create button - Websockets 

Save and you should be sorted

**Comment by dylanrjones** [comment]
> Ignore this, found the section within Synology's Application Portal to allow webhook.
> 
> For anyone in the future simply edit your reverse proxy rule. Select Customer Headers - Dropdown menu besides Create button - Websockets
> 
> Save and you should be sorted

This works for Nginx Proxy Manager in unRAID as well. Thanks!
