### ISSUE TITLE
[Feature Request] Pick Playlist/Genre/Tag

### ISSUE THREAD

**Issue by Nelinski** [LukeChannings/moviematch#21]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It would be nice to pick a tag/playlist/genre for movies. For example, we may want to watch a Christmas film but can't decide which one.

**Describe alternatives you've considered**
N/A

**Additional context**
More flexibility in picking what genres/tags/playlists to show when first "logging" into a room.

**Comment by Coleyra** [comment]
I support this feature, and i think a filter per duration would be cool too.
Like : 
- Less than 1h30
- Less than 2h
- Less than 2h30
- Less than 3h

**Comment by Mushin** [comment]
It would also be nice to filter by critic rating, release year etc.

**Comment by LukeChannings** [comment]
Fixed in #59
