### ISSUE TITLE
Request for new Release

### ISSUE THREAD

**Issue by therealshark** [LukeChannings/moviematch#24]
Hello, i wanted to use the newly added feature allowing to create links to https://app.plex.tv instead of https://{server} added here: https://github.com/LukeChannings/moviematch/pull/23

I'm using the Dockerfile and configured the LINK_TYPE. After debugging for a while (checking docker config/sourcecode/building the image myself locally) i finally realised, the latest release (and published docker image) doesn't have this changes yet.

Therefore i'm humbly requesting a new release incorporating this changes 👍

**Comment by LukeChannings** [comment]
An image for 1.3.0 is available now, thanks!
