### ISSUE TITLE
Loading Movies

### ISSUE THREAD

**Issue by dj-curls** [LukeChannings/moviematch#26]
Hi, 

I'm running into an issue running this, I get "Loading movies" in the browser, and nothing happens. 

Here's the logs:

```
oliver@XXX:~$ sudo docker run -it -e PLEX_URL=https://XXX:32400 -e PLEX_TOKEN=XXX -e LIBRARY_FILTER=Movies,Films -e LOG_LEVEL=DEBUG -p 8000:8000 lukechannings/moviematch
DEBUG Log level DEBUG
INFO Listening on port 8000
DEBUG serveFile(/app/public/index.html)
DEBUG serveFile(/app/public/style.css)
DEBUG serveFile(/app/public/js/main.js)
DEBUG serveFile(/app/public/assets/logo.svg)
DEBUG serveFile(/app/public/assets/background-grain.png)
DEBUG serveFile(/app/public/assets/background.svg)
DEBUG serveFile(/app/public/js/MovieMatchAPI.js)
DEBUG serveFile(/app/public/js/CardView.js)
DEBUG serveFile(/app/public/js/MatchesView.js)
DEBUG serveFile(/app/public/assets/icons/favicon-32x32.png)
INFO Got a login: {"name":"Oliver","roomCode":"BSBL"}
DEBUG New session created. Active session ids are: BSBL
DEBUG New user Oliver logged in
DEBUG Oliver asked for the next batch of movies
```

**Comment by LukeChannings** [comment]
Those logs look normal to me. 

What browser are you using? Can you check if there are any errors in the JavaScript Console?

If Chrome, you can open it with Cmd+Alt+J in macOS or ctrl+shift+j on Windows.

**Comment by lbarnett83** [comment]
I'm running into the same issue.  Nothing in the JS console either..

**Comment by dj-curls** [comment]
Chrome on windows. 

As the other commenter has said, nothing in the javascript console window. No pending network requests, and no messages sent over websockets asking for movies either.

**Comment by LukeChannings** [comment]
Can one of you send a screenshot of the WebSocket messages you have? It sounds like you never receive a batch message. 

In normal circumstances the message should look like this:

<img width="1237" alt="Screenshot 2021-01-06 at 07 24 35" src="https://user-images.githubusercontent.com/461449/103768304-3e3f1900-4ff0-11eb-949e-f2615afec125.png">

**Comment by dj-curls** [comment]
Yep looks like the batch message never arrives. 

![image](https://user-images.githubusercontent.com/5913916/103807527-678e9200-504e-11eb-9665-0454a038c840.png)

**Comment by LukeChannings** [comment]
Hey, just pushed v1.5.0 with some logging that might shed light on where it's falling over.
Can you update and send me the logs?

**Comment by lbarnett83** [comment]
I'm seeing the same behaviour.  As far as my docker output, nothing new in the debug log, and nothing showing up in the console
![Screenshot_2021-01-06_20-30-00](https://user-images.githubusercontent.com/17346039/103847681-14244000-505e-11eb-896f-90091868354b.png)
![Screenshot_2021-01-06_20-30-16](https://user-images.githubusercontent.com/17346039/103847683-14bcd680-505e-11eb-9bdb-5baf0cac63a3.png)

**Comment by lbarnett83** [comment]
Wait, I found something.  If I start the container, and then DON'T open the page, this happens:
![Screenshot_2021-01-06_20-30-26](https://user-images.githubusercontent.com/17346039/103848005-a9273900-505e-11eb-97e0-4208d2893cdc.png)

**Comment by LukeChannings** [comment]
Hey, I deleted your comment because you included your plex token. Can you re-upload with that blurred out?

**Comment by lbarnett83** [comment]
that was dumb of me, and thanks for catching it
coming right up

**Comment by lbarnett83** [comment]
![Screenshot_2021-01-06_20-30-26fixed](https://user-images.githubusercontent.com/17346039/103848315-4d10e480-505f-11eb-9923-c6ce81327de5.png)

**Comment by LukeChannings** [comment]
Hmm, ok, so the reason the batch is never sent is that the request to your Plex server timed out.
I *think* the default timeout is 300 seconds (5 minutes), which would explain why it appears that nothing is happening.

Can you confirm that the container can route to your Plex server?

**Comment by lbarnett83** [comment]
A revers proxy shouldn't be causing that, right?   But,  a lack of hairpin NAT might.   Gonna update the server from FQDN to IP in the container.

**Comment by lbarnett83** [comment]
Got it.  The router in front of my unraid server doesn't support NAT loopback.  When I changed from my FQDN to the http://IP:PORT format instead, I got this:
![Screenshot_2021-01-06_20-52-56](https://user-images.githubusercontent.com/17346039/103849177-4a16f380-5061-11eb-9bce-28736931f197.png)

**Comment by LukeChannings** [comment]
Yep - that looks like it's working!

**Comment by lbarnett83** [comment]
Confirmed with the page actually working.
Now I just have to find time to replace the crappy ISP router, with my Edgerouter.  Ironically, I work for the ISP that supplies the "crappy" router :smile:

**Comment by LukeChannings** [comment]
@dj-curls, can you confirm that the issue was the same for you?

**Comment by LukeChannings** [comment]
I'm going to assume it is the same issue. Feel free to re-open if you think it's something unrelated.

**Comment by dj-curls** [comment]
It was the same thing for me, however my server is hosted "in the cloud" 

I had to put this container in the same docker network as plex, and connect to the internal docker IP. 

No combination of correct external IP / DNS names worked.

**Comment by LukeChannings** [comment]
It sounds like a networking issue specific to your stack - MovieMatch / Deno don't do anything special with DNS or routing, so if the external DNS isn't accessible to MovieMatch it won't be accessible to any containers in the same configuration.

**Comment by dj-curls** [comment]
Not 100% sure how to check accessibility from inside the container, but the host has access to itself

```
curl -I http://DNSNAME:32400/library/sections?X-Plex-Token=XXX
HTTP/1.1 200 OK
X-Plex-Protocol: 1.0
Content-Type: text/xml;charset=utf-8
Content-Length: 1808
Connection: Keep-Alive
Keep-Alive: timeout=20
Cache-Control: no-cache
Date: Sat, 09 Jan 2021 13:41:15 GMT
```

So safe to assume it's something in the container / container configuration?

**Comment by LukeChannings** [comment]
If you're running Docker, you could try:

```
λ docker run -it --rm hayd/alpine-deno:1.6.2 -- /bin/sh
/ # apk update && apk add curl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
v3.12.3-47-g3428e040de [http://dl-cdn.alpinelinux.org/alpine/v3.12/main]
v3.12.3-48-gea3fd89439 [http://dl-cdn.alpinelinux.org/alpine/v3.12/community]
OK: 12756 distinct packages available
(1/4) Installing ca-certificates (20191127-r4)
(2/4) Installing nghttp2-libs (1.41.0-r0)
(3/4) Installing libcurl (7.69.1-r3)
(4/4) Installing curl (7.69.1-r3)
Executing busybox-1.31.1-r16.trigger
Executing ca-certificates-20191127-r4.trigger
Executing glibc-bin-2.32-r0.trigger
/usr/glibc-compat/sbin/ldconfig: /usr/glibc-compat/lib/ld-linux-x86-64.so.2 is not a symbolic link

OK: 19 MiB in 21 packages
/ # curl -I http://DNSNAME:32400/library/sections?X-Plex-Token=XXX
```

Update `curl -vv -I http://DNSNAME:32400/library/sections?X-Plex-Token=XXX` to be your URI.
If that resolves in might be something to do with MovieMatch, otherwise probably a Docker issue.

**Comment by dj-curls** [comment]
So that alpine container doesn't contain curl. 

I ran this: 

```
sudo docker run -it --rm curlimages/curl -L -v http://DNSNAME:32400/library/sections?X-Plex-Token=XXX
* Trying XXX:32400...
* connect to XXX port 32400 failed: Operation timed out
* Failed to connect to XXX port 32400: Operation timed out
* Closing connection 0
curl: (28) Failed to connect to direct.aande.uk port 32400: Operation timed out
```

Proves that docker containers don't like loopback on dns name or external ip. I copied and pasted the docker config from the readme. Does yours work or do you provide the internal ip of the docker container?

**Comment by dj-curls** [comment]
Oh I missed your commands on the next line down to add curl, doh!

**Comment by dj-curls** [comment]
Oh I missed your commands on the next line down to add curl, doh!

**Comment by lbarnett83** [comment]
Dj, I'm assuming you are running your domain via a reverse proxy?

**Comment by dj-curls** [comment]
Yep with traefik.

I did try with IP external address too with the same results

**Comment by lbarnett83** [comment]
Wait, when you run the movie match docker, pointing towards Plex with with WAN IP:PORT instead of domain, it STILL doesn't work, but LAN IP:PORT does work?

**Comment by dj-curls** [comment]
Yep, that's exactly what's happening, with LAN being a docker internal network, and WAN being the NIC connected to the wider network.

**Comment by clarklab** [comment]
I've got the "Loading movies..." screen and not sure what else to try. To be honest, I'm surprised I even got it installed and running. I took a peek through the rest of this thread, but most of it was over my head. Is there a "for dummies" summary that might help me?

I've got it running via docker compose on a QNAP NAS that's running the Plex server itself. And I'm bad at this.

**Comment by lbarnett83** [comment]
What does the compose file look like? Blur out the token and any outside IP
addresses.

**Comment by clarklab** [comment]
<img width="633" alt="Pasted_Image_1_18_21__9_02_PM" src="https://user-images.githubusercontent.com/160409/104982561-8b4bc380-59d0-11eb-8f7c-78e9ab62452c.png">

**Comment by lbarnett83** [comment]
Ideally, use the IP of the machine hosting the Plex server, plus the port. So if your QNAP is on 192.168.1.200, then the url should look like `http://192.168.1.290:34200`

**Comment by clarklab** [comment]
ok, correct, got that

the IP in my Plex URL and the IP that MovieMatch are running on are the same

**Comment by lbarnett83** [comment]
And it's still not working?

**Comment by clarklab** [comment]
Still not working. Stuck on 'Loading movies..."

I do have close to 2,000 movies. Think it could be a library size thing?

**Comment by lbarnett83** [comment]
Unlikely. My library is ~1600 and loads almost instantly. This feels like somehow the movie match container isn't seeing the Plex container.

**Comment by clarklab** [comment]
That's what I'm thinking, I just don't know enough how to troubleshoot what the issue might be.

**Comment by clarklab** [comment]
Watching the Network tab, the websocket stays "pending" and never seems to resolve 

![image](https://user-images.githubusercontent.com/160409/104984788-0b742800-59d5-11eb-9771-f28cd79f4d6a.png)

**Comment by LukeChannings** [comment]
The container itself looks fine, if it was a Plex <-> MovieMatch communication issue the container would crash after 5 minutes. 

Are you going via a reverse proxy? Make sure the reverse proxy can do the WebSoxket upgrade. 

There is documentation for a few different HTTP servers [here](https://github.com/LukeChannings/moviematch/blob/main/docs/reverse-proxy.markdown) that might help.

**Comment by LukeChannings** [comment]
This could also be relevant - https://github.com/LukeChannings/moviematch/issues/16#issuecomment-742894185

**Comment by 2fst4u** [comment]
I'm having this issue using only my Plex server's internal IP address. No reverse proxy (yet).

My moviematch and Plex are on different lan segments, but I've confirmed my firewall isn't blocking anything.

It just sits there on "loading movies".

**Comment by LukeChannings** [comment]
@2fst4u these things happen 😄. Logging is much more verbose in 2.0 if a provider is unavailable.
