### ISSUE TITLE
[Bug] Uncaught exception using a Docker Run

### ISSUE THREAD

**Issue by GhostPyxel** [LukeChannings/moviematch#30]
**Describe the bug**
When creating the container using docker run, exception is caught stating the following:

INFO Listening on port 8000
error: Uncaught (in promise) Error: <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
    throw new Error(await req.text())
          ^
    at getSections (plex.ts:42:11)
    at async plex.ts:74:20

Maybe it should also use another port than 8000 as it is a port used generically by apps in dev and can create conflicts in the future.

**Comment by LukeChannings** [comment]
Hey @GhostPyxel,

This error happens when the configured `PLEX_URL` returns a 404 when getting a list of libraries.
Can you double check your `PLEX_URL`?

**Comment by GhostPyxel** [comment]
Indeed, got a typo on my URL.
Gotta test that out then, thanks.
