### ISSUE TITLE
[Feature Request] - SWAG integration

### ISSUE THREAD

**Issue by rubadub-github** [LukeChannings/moviematch#32]
Do you know how to get integrated into SWAG so I can put it behind my domain for remote access along with my other apps?

Ideally a subfolder as that is how I am set up right now.

what would go in these files?

moviematch.subdomain.conf.sample and/or moviematch.subfolder.conf.sample

**Comment by LukeChannings** [comment]
I'm sorry but I haven't had any experience with SWAG (nor do I really know what it is).
If you get this working, I'm happy to accept a MR with some config and docs.

**Comment by bcpletcher** [comment]
Just to run off this as well, Swag is the new LetsEncrypt version for reverse proxy. I havent had time personally to mess around with it but these are the template files provided by Swag.

[_template.subdomain.txt](https://github.com/LukeChannings/moviematch/files/5784964/_template.subdomain.txt)
[_template.subfolder.txt](https://github.com/LukeChannings/moviematch/files/5784965/_template.subfolder.txt)

**Comment by LukeChannings** [comment]
That looks like an nginx.conf to me. I have some documentation on nginx behind a reverse proxy [here](https://github.com/LukeChannings/moviematch/blob/main/docs/reverse-proxy.markdown), which is a good starting point.

**Comment by rubadub-github** [comment]
this is required for SWAG template (for subfolder:

first go into <container_name> settings, under "General" set the URL Base to /<container_name>/ and restart the <container_name> container

**Comment by d8sychain** [comment]
SWAG is a docker developed by [linuxserver.io](linuxserver.io) 

SWAG - Secure Web Application Gateway (formerly known as letsencrypt, no relation to Let's Encrypt™) sets up an Nginx webserver and reverse proxy with php support and a built-in certbot client that automates free SSL server certificate generation and renewal processes (Let's Encrypt and ZeroSSL). It also contains fail2ban for intrusion prevention.

Hope this adds some clarification to anyone that stumbles across this.
