### ISSUE TITLE
[Bug] Holding Left or Right keys seems to lock the app

### ISSUE THREAD

**Issue by GhostPyxel** [LukeChannings/moviematch#33]
**Describe the bug**
Holding the keyboard keys "Left" and "Right" seems to rate a bunch of items than freeze the app controls (Keys are not responding) and emojis at the bottom become grayed out and unclickables. Only control left is swipe by holding the LMB.

A refresh of the page restore controls.

**To Reproduce**
1. Enter Rating Room
2. Hold Left or Right on the Keyboard for more than 3 seconds
3. Controls are locked and needs a refresh

**Expected behavior**
Controls shouldn't be locked. Maybe a limit on holding key duration is also necessary to avoid issues in the future.

![Screenshot_12](https://user-images.githubusercontent.com/52525576/103796508-981efd80-5047-11eb-86cb-d50ead1a6723.jpg)

**Comment by LukeChannings** [comment]
Hey,

I just pushed v1.5.0 with a possible fix for this. Can you try it and let me know?

**Comment by LukeChannings** [comment]
Closing this due to lack of response. Can re-open if this pops up again in the future.
