### ISSUE TITLE
[Feature Request] "Go Back" Option

### ISSUE THREAD

**Issue by GhostPyxel** [LukeChannings/moviematch#34]
**Is your feature request related to a problem? Please describe.**
We all do mistakes. A button to check back the previous movie / item would be nice  in case we rate a movie too quickly.
It could be a "One Time dealer" (only once per movie) or unlimited returns.

**Comment by LukeChannings** [comment]
I think this goes against the philosophy of the app, and it'd be extremely difficult to implement, so I'm gonna close this.
Thanks for you suggestions!

**Comment by aeiler** [comment]
Hey Luke, I appreciate the app and have really enjoyed using it...
I wanted to chime in on the "go back" enhancement request:
I disagree that it goes against the philosophy of the app (Maybe? Not really sure what your philosophy is...).

There were a few times where I genuinely misclicked and wanted to change my vote but was unable to. Especially when I accidentally downvoted something that I actually did want to watch.
If the purpose of the app is to help people match on movies they both (or groups) want to watch, then being able to accurately record their votes is very important.
