### ISSUE TITLE
[Bug] Vanilla docker run/compose raises ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by pythoninthegrass** [LukeChannings/moviematch#37]
**Describe the bug**
Chrome (Chromium) attempts to redirect to HTTPS instead of unencrypted HTTP.

**To Reproduce**
* `docker run -it -e PLEX_URL=<Plex URL> -e PLEX_TOKEN=<Your Token> -p 8000:8000 lukechannings/moviematch` or the[ docker-compose equivalent](https://github.com/LukeChannings/moviematch/blob/main/docs/docker-compose.markdown)
* Open localhost:8000
* Chromium v84.0.4147.105 raises:
```
This site can’t provide a secure connection192.168.8.151 sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR
```

**Expected behavior**
Fallback to insecure connection with scary warnings when SSL termination doesn't happen.

**Screenshots**
![2021-01-09 12_10_50-192 168 8 151 - Chromium](https://user-images.githubusercontent.com/4097471/104105471-f03a4780-5273-11eb-9550-c8c0db8745f3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (v2004 Build 19041.685)
 - Browser: Chromium
 - Version: 84.0.4147.105

**Smartphone (please complete the following information):**
- N/A

**Additional context**
I expect the results to be the same across OSes and browsers. Haven't thoroughly tested, but can if necessary. Ideally, MovieMatch would fallback to an insecure connection without an SSL cert instead of necessitating using nginx or traefik, but that sounds like the obvious upstream solution combined with Let's Encrypt or another CA's cert.

**Comment by LukeChannings** [comment]
Hey, thanks for the report!

MovieMatch does not redirect HTTP to HTTPS, and doesn't expose an option to configure TLS. 

I suspect your browser or reverse proxy is configured to redirect HTTP to HTTPS. 

The best way to successfully configure MovieMatch with TLS is with a reverse proxy that terminates TLS.

I have some examples of that config [here](https://github.com/LukeChannings/moviematch/blob/main/docs/reverse-proxy.markdown)

**Comment by pythoninthegrass** [comment]
Ugh. Suspected that might be the case. I'll see if I can get a reverse proxy working. Bit of an Achilles' heel for me haha. 

Also noticed that thumbnails are broken. I've set `ROOT_PATH` to `/docker/containers/moviematch` but noticed that it's not mounting any volumes. Can open a separate ticket, but thought I'd mention it if I'm missing something obvious.
![2021-01-09 13_44_34-MovieMatch - Chromium](https://user-images.githubusercontent.com/4097471/104107323-e0753000-5280-11eb-9d1b-8cb085ab269e.png)

Thanks for your help @LukeChannings!

**Comment by LukeChannings** [comment]
`ROOT_PATH` should only be used it you're hosting MovieMatch behind a single domain. 

For example, if you want apps.example.com/moviematch to point to MovieMatch, the ROOT_PATH should be `moviematch`. 

It does not relate to volumes 😬

**Comment by pythoninthegrass** [comment]
> `ROOT_PATH` should only be used it you're hosting MovieMatch behind a single domain.

That did it! Thumbnails are populating as expected. I'll close this ticket and look at setting up a reverse proxy.

Thanks again!
