### ISSUE TITLE
Support secure websockets when behind a reverse proxy

### ISSUE THREAD

**Issue by LukeChannings** [LukeChannings/moviematch#4]

**Comment by dlchamp** [comment]
@PTRFRLL

Like an actual share link?

If I generate a room with code JK6L, generate a https://moviematch.domain.tld/JK6L link?

**Comment by PTRFRLL** [comment]
> 
> 
> @PTRFRLL
> 
> Like an actual share link?
> 
> If I generate a room with code JK6L, generate a https://moviematch.domain.tld/JK6L link? Because this is exactly what I was about to propose.

I like that idea. This would simply allow the app to be run behind a reverse proxy. Right now, the websocket used to query for movies does not support `https` (or `wss` in this case) so the app doesn't function at all.

**Comment by zachbunyard** [comment]
Allowing this to run behind a reverse proxy would be great.

**Comment by LukeChannings** [comment]
This should work in [v1.0.2](https://github.com/LukeChannings/moviematch/releases/tag/v1.0.2)

**Comment by LukeChannings** [comment]
> @PTRFRLL
> 
> Like an actual share link?
> 
> If I generate a room with code JK6L, generate a https://moviematch.domain.tld/JK6L link? Because this is exactly what I was about to propose.

I've added another ticket to track this #7. Thanks for the suggestion!

**Comment by pconwell** [comment]
Maybe I'm not understanding, but if I go to http://192.168.1.94:8000/8FM0 (or any other randomly generated "room"), the url does not work and I just get "not found" returned. How do I send a link to a specific room?

Or am I completely mis-understanding the process?
