### ISSUE TITLE
Uncaught Error: not implemented!

### ISSUE THREAD

**Issue by kobear403** [LukeChannings/moviematch#42]
```
error: Uncaught Error: not implemented!
    at Object.signal (deno:runtime/js/40_signals.js:164:13)
    at index.ts:17:6
    at <anonymous> (<anonymous>)
```

I'm running moviematch 1.2.0 on deno 2.3.3 in vscode 1.52.1

**Comment by LukeChannings** [comment]
The latest version of MovieMatch is 1.7.0, and the latest version of Deno is 1.6.3.

Can you update to confirm your versions and your OS?

**Comment by LukeChannings** [comment]
It looks like this error was with `Deno.signal`.  Make sure you're running Deno with the `--unstable` flag.

**Comment by kobear403** [comment]
I'm following the instructions in the readme, and the `With Deno > Download the latest release` links you to moviematch v1.2.0

Downloading moviematch 1.7.0 resolved the issue!

**Comment by kobear403** [comment]
Leaving this open actually in case you want to update the readme link. I got it all working now!

**Comment by LukeChannings** [comment]
Thanks for that! I've fixed the link now.
