### ISSUE TITLE
[Feature Request] Persistent Database

### ISSUE THREAD

**Issue by MicMillon** [LukeChannings/moviematch#44]
love the app, but doesn't seam very practical, if every time i reboot or rebuild (to make a settings change) the container, i loose all history... 

Most docker images have an AppData value, where the application saves its relevant data. i didn't see any variable for that. did i miss it? 

when i do a docker inspect, i get the felling something should be configured here: (rather than null)

        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "1",
                    "max-size": "50m"
                }
            },

**Comment by LukeChannings** [comment]
See https://github.com/LukeChannings/moviematch/issues/46#issuecomment-770405729
