### ISSUE TITLE
[Feature Request] - multiple rooms and persistent rooms for different libraries/genres/etc

### ISSUE THREAD

**Issue by rubadub-github** [LukeChannings/moviematch#46]
be able to create multiple rooms for different libraries or genres or whatever.

Wife and I can swipe though grown up movies.
Kids through their movies.

or we swipe through our comedies , action, etc.

It would nice if they were customizable and persistent.  With some kind of back-end admin page or config file on the server.

**Comment by LukeChannings** [comment]
This is a pretty simple app where the rooms are designed to be ephemeral for the mostpart.
If you keep the server running then the rooms will persist.

It's possible to persist the state of rooms, but it's something that would require time and thought, and would likely require an admin page of some sort, like you suggest.

I'm just one guy, and I don't have a ton of time to throw at this project, and I also have a day job. This feature is unlikely to ever materialise unless someone else wants to contribute it.
