### ISSUE TITLE
[Bug] The object is in an invalid state.

### ISSUE THREAD

**Issue by ajgnet** [LukeChannings/moviematch#47]
**Describe the bug**
Using MovieMatch through a lighttpd reverse proxy. The site loads, but when "engage" is clicked the error, "The object is in an invalid state." appears and am unable to proceed. Works when accessed directly on port 8000 via docker.

I am using lighttpd as a reverse proxy with the following configuration:

```
$HTTP["host"] == "moviematch.example.org" {
        $SERVER["socket"] == ":443" {
                proxy.header = ( "upgrade" => "enable")
                setenv.add-request-header   = ( "Connection" => "Upgrade")
                setenv.add-response-header  = ( "Connection" => "Upgrade")
                proxy.server  = ( "" =>
                    ( "internal" =>
                        (
                            "host" => "10.0.10.2",
                            "port" => 8000
                        )
                    )
                )
        }
}
```

Possible to add a working example for lighttpd proxy?

**Comment by LukeChannings** [comment]
This is pretty strange. I can reproduce this, and it looks like the messages are only being sent in one direction (client -> server).

I don't have a lot of time to look into this right now, but I'll take a closer look later.

**Comment by gstrauss** [comment]
`proxy.header = ( "upgrade" => "enable")` enables lighttpd support in lighttpd mod_proxy for `Upgrade: ...` 

However, these look wrong.  They should be sent by the client or returned from the backend.  They should not be part of your lighttpd config.
```
                setenv.add-request-header   = ( "Connection" => "Upgrade")
                setenv.add-response-header  = ( "Connection" => "Upgrade")
```
