### ISSUE TITLE
[Bug] Port set in docker-compose apparently not used by moviewatch

### ISSUE THREAD

**Issue by ohtee** [LukeChannings/moviematch#53]
**Describe the bug**
Port set in docker-compose not used by moviewatch

**To Reproduce**
In docker-compose.yml, use:
   ports:
      - 7999:7999

then docker-compose up -d

In the browser at my NAS's IP address:7999 I cycle between ERR_EMPTY_RESPONSE and ERR_CONNECTION_RESET

So I checked the container's log which states: "INFO Listening on port **8000**"

**Expected behavior**

Load at the port set in the compose file.

**Additional context**

This is on a Synology NAS.

**Comment by LukeChannings** [comment]
Hey @ohtee 

If you need to change the port that MovieMatch listens on you can set the `PORT` environment variable (e.g. `PORT=7999`).

Is there a reason you don't want to set the following in your docker-compose?

```yaml
ports:
  - 7999:8000
```

Please see the compose file documentation for [ports](https://docs.docker.com/compose/compose-file/compose-file-v3/#ports) and [environment](https://docs.docker.com/compose/compose-file/compose-file-v3/#environment), as well as MovieMatch's [available configuration options](https://github.com/LukeChannings/moviematch#configuration) for available environment variables.

**Comment by ohtee** [comment]
That solved it, thanks! I'm an idiot and it's not the first time I get confused between host ports and container ports.
