### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Flowake** [LukeChannings/moviematch#64]
**Is your feature request related to a problem? Please describe.** 
When setting up movie match behind a reverse proxy, the pictures will only load if the location "/" is proxied to the movie match port. But this location is also be used to display an html webpage in my case.

**Describe the solution you'd like**
It would be good if Moviematch only required to proxy pass the location '/moviematch' in the case of subpath Nginx.

**Describe alternatives you've considered**
I'm not really sure if it's possible to do this, or if it is only a bug on my side.

**Additional context** 

What I see when I don't redirect '/' to Moviematch port.
![image](https://user-images.githubusercontent.com/58951320/112396226-11052b80-8d00-11eb-93dd-fd83fce125f0.png)

**Comment by LukeChannings** [comment]
Have you tried setting the `ROOT_PATH` environment variable to "/moviematch"?

[docs](https://github.com/LukeChannings/moviematch/tree/v1#configuration)

**Comment by Flowake** [comment]
I set BASE_PATH = /moviematch, but I don't see any ROOT_PATH variable in the README. Maybe I don't have the right version. From what I see I'm at 1.7.0.

**Comment by LukeChannings** [comment]
Can you upgrade to v1.10.0 and try it with `ROOT_PATH`?

The environment variables are different between v1 and (unreleased) v2, which is causing confusion here.

**Comment by Flowake** [comment]
How can I specify the version ? I'm using the following command, and it seems that the version 1.7.0 is getting installed.
`docker run -it -e PLEX_URL=<Plex URL> -e PLEX_TOKEN=<Your Token> -p 8000:8000 lukechannings/moviematch`

**Comment by LukeChannings** [comment]
`sudo docker run -it -e PLEX_URL=xxxxx:32400 -e PLEX_TOKEN=xxxxxxx -e ROOT_PATH=/moviematch -p 8000:8000 --restart always lukechannings/moviematch:1.10.0`

Or

`sudo docker run -it -e PLEX_URL=xxxxx:32400 -e PLEX_TOKEN=xxxxxxx -e ROOT_PATH=/moviematch -p 8000:8000 --restart always --pull always lukechannings/moviematch:latest`

**Comment by Flowake** [comment]
Ok thanks for your help, it works just fine !
