### ISSUE TITLE
[Feature Request] Change background color and top logo

### ISSUE THREAD

**Issue by morganzero** [LukeChannings/moviematch#67]
**Describe the solution you'd like**
I'd like the ability to switch out the top logo and the ability to change the background color.

**Comment by LukeChannings** [comment]
v2 has a less contrasting theme, and will support a dark mode eventually.

I have no plans to white-label MovieMatch, but feel free to fork it and change the logo yourself.

**Comment by morganzero** [comment]
Thanks for replying. Which tag do I use for V2 in docker?

**Comment by LukeChannings** [comment]
The latest alpha is `2.0.0-alpha.4`, and alpha 5 will be available this weekend with some important bug fixes.

The release after alpha 5 will be beta 1, which will be available under the `develop` tag.
