### ISSUE TITLE
[Feature Request] Add arm Linux builds

### ISSUE THREAD

**Issue by flying-sausages** [LukeChannings/moviematch#68]
**Is your feature request related to a problem? Please describe.** 
There's no ARM builds so source builds are required there

**Describe the solution you'd like** 
Linux Armv8 builds

**Describe alternatives you've considered** 
Running it from source

**Additional context** 
The recent 2.0.0-alpha builds are missing those so I'm not sure if it's planned or not. I see Apple Silicon builds so it would be nice to target Raspberry Pis and other ARM-based systems too.

**Comment by LukeChannings** [comment]
Hey @flying-sausages 

Yeah I've been thinking about this too. It's possible, but not simple since Deno doesn't have official support for ARM64 on Linux yet (I'm compiling it myself at the moment).

**Comment by LukeChannings** [comment]
The latest release has an ARM64 binary
