### ISSUE TITLE
Improve room code ergonomics 

### ISSUE THREAD

**Issue by LukeChannings** [LukeChannings/moviematch#7]
It's hard to share the code, and there are situations when a room code isn't really needed at all. 

- add an option to disable room codes
- implement a share sheet for the room code to make it easier to share

**Comment by pconwell** [comment]
I also posted in #4, and I think this might be a similar request here.

I'd like a way to send a link to a specific room. For example, I send my wife a text with a link to `http://192.168.1.94:8000/XXXX` and she can just click the link and type in her name. Or even better may be an option to send a link like `http://192.168.1.94:8000/XXXX#wife` or `http://192.168.1.94:8000/XXXX?user=wife` or whatever the proper formatting would be. Obviously, this would create a bit more work on my end, but I think reducing friction for certain users would make life a lot easier in  the long run.

**Comment by LukeChannings** [comment]
Hey Patrick,

The current version does not support deep linking to a room code.

I'm working on a new version that includes both deep linking and sharing. 

It will look something like this:

<img width="1061" alt="Screenshot 2021-01-06 at 23 07 53" src="https://user-images.githubusercontent.com/461449/103849931-0974a580-5074-11eb-8123-2d5109328070.png">

**Comment by pconwell** [comment]
Sorry for the late reply, work has been busy. This looks great! Thank you

**Comment by LukeChannings** [comment]
This is fixed in `2.0.0-alpha.1`, with the caveat that:

1. Tapping the share icon will copy the current URL (with a `roomName=<roomName>` query parameter)
2. Sharing will not work for non-HTTPS websites on iOS (I will add a message about this)
