### ISSUE TITLE
Uncaught (in promise)

### ISSUE THREAD

**Issue by Element115sw** [LukeChannings/moviematch#8]
I am getting this error. 

```
[34mINFO Listening on port 8000[39m
[0m[1m[31merror[0m: Uncaught (in promise) Error: <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
throw new Error(await req.text())
```

Any ideas?

**Comment by LukeChannings** [comment]
Looks like your Plex token isn't valid.

If you navigate to `<PLEX_URL>/library/sections?X-Plex-Token=<PLEX_TOKEN>` in a browser it should load some XML and not give you an Unauthorized error.

**Comment by Element115sw** [comment]
Thanks for the help! The xml is fine.

I changed my `PLEX_URL` from `http://192.168.8.10:32400` to `192.168.8.10:32400` and now get this.


```
[0m[1m[31merror[0m: Uncaught (in promise) URIError: relative URL without a base
at [0m[1m[3mprocessResponse[0m ([0m[36mcore.js[0m:[0m[33m223[0m:[0m[33m11[0m)
at [0m[1m[3mObject.jsonOpAsync[0m ([0m[36mcore.js[0m:[0m[33m240[0m:[0m[33m12[0m)
at [0m[38;5;8masync [0m[0m[1m[3m[38;5;8mfetch[0m [0m[38;5;8m([0m[0m[38;5;8mdeno:op_crates/fetch/26_fetch.js[0m[0m[38;5;8m:[0m[0m[38;5;8m1274[0m[0m[38;5;8m:[0m[0m[38;5;8m29[0m[0m[38;5;8m)[0m
at [0m[38;5;8masync [0m[0m[1m[3mgetSections[0m ([0m[36mplex.ts[0m:[0m[33m23[0m:[0m[33m15[0m)
at [0m[38;5;8masync [0m[0m[36mplex.ts[0m:[0m[33m60[0m:[0m[33m20[0m
```

**Comment by LukeChannings** [comment]
The `http://192.168.8.10:32400` URL what it should be. I've pushed some better logging into the docker latest, can you give that a try?

**Comment by Element115sw** [comment]
I renewed the Token, tried the xml link again to be sure and updated the plex docker with the new token and that is working as well.

This is the error now.
```

[0m[1m[31merror[0m: Uncaught (in promise) Error: Authentication error: http://192.168.8.10:32400/library/sections?X-Plex-Token=claim-<rest of token>

throw new PlexTokenError(`Authentication error: ${req.url}`)
```

**Comment by LukeChannings** [comment]
The `claim-` prefix stands out to me. When you paste the URL from `Authentication error: <URL>` into an incognito browser it definitely loads the XML instead of giving you `401 Unauthorized`?

Also how did you acquire your token?

**Comment by Element115sw** [comment]
> Also how did you acquire your token?

Yup that was it...... I am a dumbass. I remembered where i got the token from https://www.plex.tv/claim/ for the plex container, without following your guide. Sry for keeping you busy.

**Comment by LukeChannings** [comment]
No worries :) I've added a check to make sure the token looks right, so the error will at least be nicer next time.
