### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by vishhvaan** [LukeChannings/moviematch#83]
Please fill out:

- **MovieMatch version:** v1
- **System:** Docker
- **Plex Version:** 1.23

**Describe the bug** Hello again. I have been putting together my web server again and I followed the configuration we discussed before and on the Github but I am again failing to get the website to display as a subfolder on a domain. 

**To Reproduce** Steps to reproduce the behavior:
docker-compose:
131   moviematch:
132    image: lukechannings/moviematch:latest
133    container_name: moviematch   
134    environment:                         
135     PLEX_URL: "http://***:32400"
136     PLEX_TOKEN: "****"
137     ROOT_PATH: "/moviematch"
138    ports:                  
139       - 8000:8000

nginx .conf
 11 location ^~ /moviematch/ {
 29     set $upstream_proto http;
 30     proxy_pass $upstream_proto://moviematch/;
 31     proxy_pass_header Content-Type;
 35 }

**Expected behavior** 
Moviematch on the subfolder.

**Screenshots**

![image](https://user-images.githubusercontent.com/34782145/123550943-a4a22a00-d73d-11eb-9dec-2b89a56990dd.png)

**Desktop:**

- Browser Chrome
- Version 91

**Comment by LukeChannings** [comment]
Hey Vish,

It looks like the paths are correct based on the HTML in your screenshot.
This looks suspicious: `proxy_pass $upstream_proto://moviematch/;`
Can you use the `nginx.conf` from [the docs](https://github.com/LukeChannings/moviematch/blob/main/docs/reverse-proxy.markdown#behind-a-subpath) and see if that works?

It looks like what's happening is that you're proxying `/moviematch/$1` to `/moviematch/$1` on the backend, but you should be proxying `/moviematch/$1` to `/$1` on the backend.

**Comment by vishhvaan** [comment]
Thanks so much for your tip Luke. I exactly copied the doc and it seems to work! The moviematch above was due to me using the upstream command in nginx:

16 upstream moviematch {
17     server ***:8000;
18 }

But I just won't use that for now. Thanks again!
