### ISSUE TITLE
[Bug] Suggestions Don't Pull From Multiple Libraries

### ISSUE THREAD

**Issue by silentArtifact** [LukeChannings/moviematch#85]
**⚠️ Before filing a bug please be sure to have read the
[FAQ](https://github.com/LukeChannings/moviematch#faq) and search through
[existing issues](https://github.com/LukeChannings/moviematch/issues?q=is%3Aissue)
that might be the same as your problem. If you have a feature suggestion, please
write about it in
[Discussions](https://github.com/LukeChannings/moviematch/discussions). Thanks!
⚠️**

Please fill out:

- **MovieMatch version:** 1.10
- **System:** Synology
- **Plex Version:** 1.23.4.4712 

**Describe the bug** When multiple libraries are selected using LIBRARY_TYPE_FILTER and LIBRARY_TITLE_FILTER, it pulls titles from the first library selected exclusively.

**To Reproduce** Steps to reproduce the behavior:

Select multiple libraries using LIBRARY_TYPE_FILTER or LIBRARY_TITLE_FILTER, view UI.

**Expected behavior** 

Titles from multiple libraries should be presented.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Comment by LukeChannings** [comment]
What values do you have for `LIBRARY_TYPE_FILTER` and `LIBRARY_TITLE_FILTER`?
