### ISSUE TITLE
[Bug] unable to find user deno: no matching entries in passwd file

### ISSUE THREAD

**Issue by morganzero** [LukeChannings/moviematch#87]
- **MovieMatch version:** Develop
- **System:** Docker
- **Plex Version:** PMS Docker Public

**Describe the bug** When rebuilding my container with the `:develop` tag I get this error message: `unable to find user deno: no matching entries in passwd file`.

**Comment by LukeChannings** [comment]
I can't reproduce this in the x86 or arm image. Can you make sure you've pulled the latest `:develop` image, and also try explicitly using `lukechannings/moviematch:2.0.0-beta.2`?

**Comment by morganzero** [comment]
Yeah, I tried pulling from `:develop` and `:2.0.0-beta.2`. Both give me the same output, unfortunately.

**Comment by LukeChannings** [comment]
Can you tell me more about your system?

OS: Linux or macOS or Windows
Architecture: x86_64 or aarch64
Docker version: ?

Can you send me the output of:

```bash
docker pull lukechannings/moviematch:develop
docker images lukechannings/moviematch:develop
```

**Comment by morganzero** [comment]
OS: Linux
Architecture: x86_64
Docker version: 20.10.7

Output pull:
```
develop: Pulling from lukechannings/moviematch
345e3491a907: Pull complete
57671312ef6f: Pull complete
5e9250ddb7d0: Pull complete
4b6b5b05f26b: Pull complete
c0c4ba330ce5: Pull complete
d5de6125c035: Pull complete
Digest: sha256:a7649647ed77788efe5e59e9ca93493e3857039d8da0e9f98c9f3bb7bfe4fcaf
Status: Downloaded newer image for lukechannings/moviematch:develop
docker.io/lukechannings/moviematch:develop
```

Output images:
```
REPOSITORY TAG IMAGE ID CREATED SIZE
lukechannings/moviematch develop f854d96d5793 2 months ago 238MB
```

Best,
Morgan

**Comment by morganzero** [comment]
Hmm. When rebuilding via docker-compose again I got it to work.
![bild](https://user-images.githubusercontent.com/57449785/126943979-cc10872b-c7bf-457e-9f8c-626af27fe6a8.png)

Now the odd thing is that when I use a reverse proxy again, this is what shows:
![bild](https://user-images.githubusercontent.com/57449785/126943927-c25ff3e5-22b0-459f-8e6e-21020acb5d39.png)
Any ideas?

**Comment by LukeChannings** [comment]
I suspect you had a stale `:develop` image. The second screenshot looks fine to me. If it was displaying as plain text you're possibly not forwarding `content-type` headers in your reverse proxy.

Docker Compose can be a bit finicky, to ensure it's using the latest image you need to:

```
docker-compose pull && docker-compose up -d
```

You might need to pass `--force-recreate` too
