### ISSUE TITLE
[Feature Request] Jellyfin compatibility

### ISSUE THREAD

**Issue by Tzundoku** [LukeChannings/moviematch#89]
Quite unfamiliar with coding so I'm not sure if this is a reasonable request but would love to see this integrated with Jellyfin. Thanks for your work!

**Comment by LukeChannings** [comment]
Same as https://github.com/LukeChannings/moviematch/issues/49. Note though that 2.0 has a provider abstraction, so implementing Jellyfin / Emby support will be easier.

I haven't had a lot of spare time lately (and I'm starting a Masters so am likely to have even less spare time), so 2.0 is pretty far from being finalised (although the latest beta is pretty stable).

**Comment by Tzundoku** [comment]
Appreciate the prompt reply. Best of luck with your Masters!
