### ISSUE TITLE
What is my Plex URL?

### ISSUE THREAD

**Issue by ITCMD** [LukeChannings/moviematch#98]
The install command has a spot for a plex url. Should this be a public-facing url? Should this be the ip address of my server? Should I include the 32400 port?

Thanks!

**Comment by LukeChannings** [comment]
It should be in the form: `https://plex.example.com:32400`.

Normal networking rules apply - if MovieMatch is running on your local network then you can use an IP address, if it's not you'll need to use a public-facing URL.

**Comment by ITCMD** [comment]
Awesome, thank you!
